name = "ticket-godbattle"
main = "bot.py"
compatibility_date = "2023-03-20"  # Use a recent date

[var]
BOT_TOKEN = "MTQ3NDk4NjM1OTkzNTQ3MTY2Nw.GN8QKj.pGeN98vFBpdqw2VVcxAzvHZQKkf-52oF0nMxSs"
GUILD_ID= "1400134143626448957"
BUY_SKIN_CATEGORY_ID="1445246243000553522"
DONATION_CATEGORY_ID="1464195372724523247"
POV_CATEGORY_ID="1445246310839226611"
GENERAL_CATEGORY_ID="1445246421438693591"
REPORT_PLAYERS_CATEGORY_ID="1445246498282668054"
SUPPORT_ROLE_ID="1430785610922197032"
LOG_CHANNEL_ID="1464193568230084650"